name: Textual Web MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with the Python version you want to use
    - name: Install dependencies
      run: |
        pip install textual-web
    - name: Run Textual Web
      run: |
        textual-web
